site_name: NZDGGS documentations
repo_name: thespatiallabatLaurier/nzdggs
repo_url: https://github.com/thespatiallabatLaurier/nzdggs
theme: 
  name: readthedocs
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - instant

copyright: Copyright &copy; 2019 - 2020 TheSpatiallab
